### ISSUE TITLE
Give means to configure the HTML provided to users

### ISSUE THREAD

**Issue by giuscri** [gi0baro/ovpn-portal#1]
Right now I waste ~30 minutes per day (+ context switching) helping vpn users. The issues can typically be solved by making them restarting the VPN client, forcing their laptop to use DNS from Google or CloudFlare or something along the lines.

What if we allow to configure the text of HTML provided to the users? One can use that text to provide info on
- who to ping for help throughout the organisation
- to check the dns settings if the browser is replying with dns errors
- to check the connection to a specific organisation's url that's protected by the VPN
- ...

This is an example for a possible Helm chart value

```
config:
  caveats: | # This can be Markdown rendered
    **Make sure you restart ...**. If you have any issue please
    <a href="mailto:zoo@example.com">send an email to zoo@example.com</a> 
```

What do you think? cc @edubacco @alessandrolorenzi

**Comment by gi0baro** [comment]
I would rather prefer to see a generic customisation of the templates implemented, but then supporting the styling would be quite hard.

The two templates involved are:
- https://github.com/gi0baro/ovpn-portal/blob/master/ovpn_portal/templates/index.html
- https://github.com/gi0baro/ovpn-portal/blob/master/ovpn_portal/templates/exchange.html

Maybe we can "just" support customisation of the `p` blocks in such templates via config? WDYT @giuscri ?

**Comment by giuscri** [comment]
That would suffice. What do you think of something along the lines of
```
index.paragraph_html: |
	This utility will help you to get a VPN configuration.<br/> You will need to sign in with your ORG_NAME account, ...

exchange.paragraph_html: ...
```
in app.yaml?

**Comment by giuscri** [comment]
Things are improving over time. The only cases where people are having troubles connecting are the ones where there's really the need of a person having access to the VPN configurations.

Closing this in favour of https://github.com/gi0baro/ovpn-portal/pull/2
